= SATOSA Relying Party Manager

== Übersicht

.Dieser Container liefert:
* Die Webanwendung als Container mit lokaler SQLITE Datenbank;
* Die HTTP-Schnittstelle am konfigurierten Docker Netzwerk
* Logfiles aus STDOUT und STDERR (Anwendung) und am volume /var/log/


== Funktion der Webanwendung

In dieser Webanwendung wird konfiguriert, welche SPs/RPs den Backend IDP verwenden können.

Der Container beinhaltet folgende Objekte/Services/etc.:

|===
| Artefakt | Wert | Beschreibung
| APPHOME | /opt/satosa_rpmgr | App Root Directory
| satosa_rpmgr  | https://github.com/identinetics/satosa_rpmgr | Source Repo
| Django Konfiguration | satosa_rpmgr.settings | Django Settings Modul
| Logging | STDOUT/STDERR |
| Startscript | /opt/bin/start.sh |
|===


== Vorbereitung der Installation

Die Webanwendung ist mit einem Docker Container (Image rpmgr) realisiert.

Das Service wird über einen externen Proxy angebunden, der TLS terminiert.

Die Daten werden in der internen SQL-Lite Datenbank gespeichert.


== Installation und Konfiguration

Dieser Arbeitsschritt orientiert sich am Ablauf des Jenkins Jobs.

Die Default-Konfiguration braucht nicht geändert werden.


== Backup/Restore

Die Datensicherung erfolgt, indem der Container terminiert wird und dann folgendes Verzeichniss gesichert wird:

    /var/lib/docker/volumes/rpmgr.database/_data/*

Für das Recovery wird die Daten db.sqllite3 vom Backup zurückzuholen.


Als zweite Möglichkeit kann man auf App-Ebene ein Recovery durchführen:

    * `docker-compose down`
    * `docker volume rm postgres_dev.data`
    * `docker-compose up -d`
    * `manage.py migrate`
    * `manage.py createsuperuser`
    * `manage.py loaddata database/database.json`

== Logging

Die Webanwendung loggt auf stdout/stderr.
Die Logfiles werden außerhalb des Containers verwaltet, z.B. mit `docker logs` oder einem Logging Driver.


== Monitoring

Port Monitoring auf dem HTTP-Port muss Status 302 mit Location auf /admin/ ergeben.

== Signal Handling

Um `docker stop` korrrekt zu verarbeiten, wird beim anfänglichen SIGTERM ein graceful shutdown eingeleitet.

Erklärung: Docker verwendet von Haus aus 2 Signale:

   * `docker stop` sendet erst SIGTERM, dann SIGKILL
   * `docker kill --signal=<signal>` kann jedes Signal senden.

Dieser Container leitet (beim Aufruf mit /opt/bin/start) SIGTERM sowohl an nginx (-> SIGQUIT) als auch gunicorn (-> SIGTERM) weiter.
Damit wird ein graceful shutdown eingeleitet.

Beim Aufruf von rotate_logs.sh wird intern ein USR1 Signal an den jeweiligen Prozess gesendet.